[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask==3.0.0",
    "flask-cors==4.0.0",
    "flask-sqlalchemy==3.1.1",
    "psycopg2-binary==2.9.9",
    "pyjwt==2.8.0",
    "werkzeug==3.0.1",
]
